### PR TITLE
Add list of "RoutingPolicyRule" objects to GraphQL "RoutingPolicy" object

### PR DESCRIPTION
**Pull request by gellis713**
This is a straightforward addition of rules to the RoutingPolicy GraphQL results so the policy has all the relevant bits in one place.

### CODE REVIEW

**Comment by pl0xym0r** [comment]
why not adding the same logic on PrefixListType ?

**Comment by gellis713** [comment]
> why not adding the same logic on PrefixListType ?

My original intent was to solve an issue I was facing but since these changes are simple enough I have followed the same paradigm for PrefixListType and CommunityListType

**Comment by gellis713** [comment]
@pl0xym0r Do you know if the maintainers have any regular cadence in reviewing merge requests?

**Comment by pl0xym0r** [comment]
@gellis713 unfortunately no, can be done in days or months

**Pull request merged**
