### PR TITLE
Netbox 4.0 compatibility

### PR DESCRIPTION
**Pull request by pl0xym0r**
This is a draft to migrate the plugin to netbox 4.0 following @peteeckel guide https://github.com/peteeckel/netbox-plugin-dns/pull/153  + https://github.com/netbox-community/netbox/blob/feature/docs/plugins/development/migration-v4.md

- Replaced references to `extras.plugins` with `netbox.plugins`
- Adjusted the menu item buttons to the new UI look by removing the colors + adding import buttons
- Changed the actions attributes in views to be dictionaries instead of tuples **-->**
>NB:  if all `actions` needed --> it's in the table
> otherwise each action must be provided in the view as a dict from https://github.com/netbox-community/netbox/blob/feature/netbox/netbox/constants.py
- Adding `brief_fields` for all serializers matching + `nested=True` for nested ones
- Redrafting all the API tests
- Reworked the whole GraphQL support to work with Strawberry
- Migrated fieldsets of Forms to the new `FieldSet` class
- Reworked the HTML templates for buttons 
- Bulk delete/edit/import on every objects seen on menu (the 3 rules objects are missing)

Remaining to check/do:
- API tests : Graphql
- test models
@k01ek As the 3 objects rules do not have links + plugin buttons on the netbox "main" view, do you think it could be nice to have them in the plugin navigation or not? It would be nice for bulk actions but it would be "heavier" for the navigation as it adds 3 objects on the menu.
@k01ek Model BGPBase : as only model Community uses it, do you want to keep it? Or integrate the parameters into the community class in order to remove BGPBase? or reuse BGPBase for others models? What was the idea to have ipam.Role + dcim.Site on a community ?

### CODE REVIEW

**Comment by pl0xym0r** [comment]
fix #187

**Comment by pl0xym0r** [comment]
The plugin can be delivered as is for 4.0, missing tests will be added later

**Comment by pl0xym0r** [comment]
closes #190

**Comment by ingvaldlorentzen** [comment]
Could we get a release of this to PyPI?

**Comment by darkcloud784** [comment]
> Could we get a release of this to PyPI?

I second this, would love to be able to update my netbox to 4.0

**Pull request merged**
